import { db } from "../firebase/firebase";
import VendorNavbar from "../components/VendorNavbar";
import { FaPlus } from "react-icons/fa";
import ProductCard from "../components/ProductCard";
import { useEffect, useState } from "react";
import { collection, getDocs, addDoc } from "firebase/firestore";
import { useAuth } from "../auth/AuthProvider";
import { Navigate } from "react-router";
import { Item } from "../types/Item";

// AddCard is used at the end of the product list to add new products for vendors
const AddCard = ({ openModal }: { openModal: () => void }) => (
  <div
    className="w-40 h-auto border-2 border-purple-300 rounded-lg flex items-center justify-center m-5 text-purple-400 hover:bg-purple-100 transition font-abel"
    onClick={openModal}
  >
    <FaPlus size={30} />
  </div>
);


export default function VendorProductCatalogue() {
  // Check for client/vendor status
  const { user, role } = useAuth();

  if (!user) {
    return <Navigate to="/login" />;
  }

  if (role !== "vendor") {
    return <Navigate to="/" />;
  }

  // Initialize state variables
  const [products, setProducts] = useState<Item[]>([]);
  const [showModal, setShowModal] = useState(false);
  const [loadingProducts, setLoadingProducts] = useState(true);
  const [newProduct, setNewProduct] = useState<Item>({
    
    id: "", // ID will be auto-generated by Firestore db when product is created here
    name: "",
    price: 0,
    description: "",
    image: "",
  });

  // modal visibility boolens handleing
  const openModal = () => setShowModal(true);
  const closeModal = () => setShowModal(false);
  
  // Fetch products from Firestore based on the products' ids
  useEffect(() => {
    const fetchProducts = async () => {
          try {
            const snapshot = await getDocs(collection(db, "products"));
            const productList = snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() })) as Item[];
            setProducts(productList);
          } catch (error) {
            console.error("Failed to fetch products:", error);
          } finally {
            setLoadingProducts(false);
          }
        };
    
        fetchProducts();
      }, []);
  

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setNewProduct((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  // Handle form submission to add the new product
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      // Add the new product to Firestore
      const docRef = await addDoc(collection(db, "products"), newProduct);
      console.log("Product added with ID:", docRef.id);

      setProducts((prevProducts) => [
        ...prevProducts,
        { ...newProduct, id: docRef.id },
      ]);

      // Close modal and also reset form
      closeModal();
      setNewProduct({
        id: "",
        name: "",
        price: 0,
        description: "",
        image: "",
      });
    } catch (error) {
      console.error("Error adding product:", error);
    }
  };

  return (
    <>
      <VendorNavbar />
      <div className="flex flex-col items-center px-5 font-abel mt-10">
        <div className="flex flex-col items-center w-full">
          <div className="flex w-full justify-center gap-150 mb-10">
            <h2 className="text-5xl font-light my-6">PRODUCTS</h2>
            <h2 className="text-5xl font-light my-6">PRODUCTS</h2>
          </div>

          <div className="m-10">
            <div className="flex flex-wrap">
              {products.map((product) => (
                <ProductCard
                  key={product.id}
                  productId={product.id}
                  name={product.name}
                  price={product.price}
                  description={product.description}
                  image={product.image}
                  vendor={true} //vendor boolean
                />
              ))}
              {/* Render AddCard to trigger modal for adding new products */}
              <AddCard openModal={openModal} />
            </div>
          </div>

          {/* Modal for adding a new product */}
          {showModal && (
            <div className="fixed inset-0 flex bg-transparent backdrop-blur justify-center items-center z-50">
              <div className="bg-white p-8 rounded-lg shadow-lg w-1/3 max-w-lg">
                <h2 className="text-2xl font-abel mb-6 text-purple-500">
                  Add New Product
                </h2>
                <form onSubmit={handleSubmit}>
                  <div className="mb-6">
                    <label className="block text-gray-700 text-sm font-abel">
                      Product Name
                    </label>
                    <input
                      type="text"
                      name="name"
                      value={newProduct.name}
                      onChange={handleInputChange}
                      className="w-full p-3 border-2 border-purple-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                      required
                    />
                  </div>
                  <div className="mb-6">
                    <label className="block text-gray-700 text-sm font-abel">
                      Price
                    </label>
                    <input
                      type="number"
                      name="price"
                      value={newProduct.price}
                      onChange={handleInputChange}
                      className="w-full p-3 border-2 border-purple-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                      required
                    />
                  </div>
                  <div className="mb-6">
                    <label className="block text-gray-700 text-sm font-abel">
                      Description
                    </label>
                    <input
                      type="text"
                      name="description"
                      value={newProduct.description}
                      onChange={handleInputChange}
                      className="w-full p-3 border-2 border-purple-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                      required
                    />
                  </div>
                  <div className="mb-6">
                    <label className="block text-gray-700 text-sm font-abel">
                      Image URL
                    </label>
                    <input
                      type="text"
                      name="image"
                      value={newProduct.image}
                      onChange={handleInputChange}
                      className="w-full p-3 border-2 border-purple-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                      required
                    />
                  </div>
                  <div className="flex justify-between gap-4">
                    <button
                      type="submit"
                      className="bg-purple-500 text-white py-2 px-6 rounded-lg font-semibold hover:bg-purple-600 transition"
                    >
                      Add Product
                    </button>
                    <button
                      type="button"
                      onClick={closeModal}
                      className="bg-gray-500 text-white py-2 px-6 rounded-lg font-semibold hover:bg-gray-600 transition"
                    >
                      Cancel
                    </button>
                  </div>
                </form>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
